[2014-09-05 11:07:09] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '=')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '=', '6,4,3')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '=', '6,4,3')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '=', '6,4,3')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '=', '6,4,3')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:08:13] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '=')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '=', '11,9,8')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '=', '11,9,8')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '=', '11,9,8')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '=', '11,9,8')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:09:13] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '=')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '=', '3,4,5')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '=', '3,4,5')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '=', '3,4,5')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '=', '3,4,5')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:09:18] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '=')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '=', '3,4,5')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '=', '3,4,5')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '=', '3,4,5')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '=', '3,4,5')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:09:58] log.ERROR: 500 - Missing argument 2 for Illuminate\Database\Query\Builder::whereIn() @ /messages
exception 'ErrorException' with message 'Missing argument 2 for Illuminate\Database\Query\Builder::whereIn()' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:551
Stack trace:
#0 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(551): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', '/home/htdocs/tu...', 551, Array)
#1 [internal function]: Illuminate\Database\Query\Builder->whereIn('3,4,5')
#2 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('3,4,5')
#5 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#7 [internal function]: Contact->whereIn('3,4,5')
#8 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#9 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('3,4,5')
#11 [internal function]: MessagesController->store()
#12 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#22 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#23 {main} [] []
[2014-09-05 11:10:07] log.ERROR: 500 - Missing argument 2 for Illuminate\Database\Query\Builder::whereIn() @ /messages
exception 'ErrorException' with message 'Missing argument 2 for Illuminate\Database\Query\Builder::whereIn()' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:551
Stack trace:
#0 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(551): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', '/home/htdocs/tu...', 551, Array)
#1 [internal function]: Illuminate\Database\Query\Builder->whereIn('3,4,5')
#2 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('3,4,5')
#5 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#7 [internal function]: Contact->whereIn('3,4,5')
#8 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#9 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('3,4,5')
#11 [internal function]: MessagesController->store()
#12 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#22 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#23 {main} [] []
[2014-09-05 11:12:31] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '=')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '=', Array)
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '=', Array)
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '=', Array)
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '=', Array)
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:14:32] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '11,9,8')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '11,9,8')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '11,9,8')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '11,9,8')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(95): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(95): Contact::whereIn('id', '11,9,8')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:15:03] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '11,9')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '11,9')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '11,9')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '11,9')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(95): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(95): Contact::whereIn('id', '11,9')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:20:25] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '1,2,3,4,5,6')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '1,2,3,4,5,6')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '1,2,3,4,5,6')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '1,2,3,4,5,6')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '1,2,3,4,5,6')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:20:46] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '1,2,3,4,5,6')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '1,2,3,4,5,6')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '1,2,3,4,5,6')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '1,2,3,4,5,6')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '1,2,3,4,5,6')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:24:29] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '1,2,3,4,5,6')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '1,2,3,4,5,6')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '1,2,3,4,5,6')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '1,2,3,4,5,6')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '1,2,3,4,5,6')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:26:49] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '=')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '=', Array)
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '=', Array)
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '=', Array)
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '=', Array)
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:27:07] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '=')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '=', 1)
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '=', 1)
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '=', 1)
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '=', 1)
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 11:27:49] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '=')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '=', 1)
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '=', 1)
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '=', 1)
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '=', 1)
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 12:01:59] log.ERROR: 500 - syntax error, unexpected ',' @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ','' in /home/htdocs/turnos/app/controllers/MessagesControler.php:96
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 12:02:54] log.ERROR: 500 - syntax error, unexpected ',' @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ','' in /home/htdocs/turnos/app/controllers/MessagesControler.php:96
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 12:03:01] log.ERROR: 500 - syntax error, unexpected ',' @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ','' in /home/htdocs/turnos/app/controllers/MessagesControler.php:96
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 12:03:27] log.ERROR: 500 - array_merge(): Argument #2 is not an array @ /messages
exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:565
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_merge(): ...', '/home/htdocs/tu...', 565, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(565): array_merge(Array, '7,6')
#2 [internal function]: Illuminate\Database\Query\Builder->whereIn('id', '7,6')
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->__call('whereIn', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->whereIn('id', '7,6')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2636): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Database\Eloquent\Model->__call('whereIn', Array)
#8 [internal function]: Contact->whereIn('id', '7,6')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2650): call_user_func_array(Array, Array)
#10 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Database\Eloquent\Model::__callStatic('whereIn', Array)
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Contact::whereIn('id', '7,6')
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 12:06:41] log.ERROR: 500 - Call to undefined function get() @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function get()' in /home/htdocs/turnos/app/controllers/MessagesControler.php:96
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 12:08:32] log.ERROR: 500 - array_key_exists(): The first argument should be either a string or an integer @ /messages
exception 'ErrorException' with message 'array_key_exists(): The first argument should be either a string or an integer' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Support/Collection.php:67
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_key_exist...', '/home/htdocs/tu...', 67, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Support/Collection.php(67): array_key_exists(Array, Array)
#2 /home/htdocs/turnos/app/controllers/MessagesControler.php(96): Illuminate\Support\Collection->get(Array)
#3 [internal function]: MessagesController->store()
#4 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#5 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#10 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#14 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#15 {main} [] []
[2014-09-05 12:42:06] log.ERROR: 500 - Call to a member function get() on a non-object @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function get() on a non-object' in /home/htdocs/turnos/app/controllers/MessagesControler.php:97
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 12:45:53] log.ERROR: 500 - Argument 1 passed to Illuminate\Database\Grammar::columnize() must be of the type array, integer given, called in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 111 and defined @ /messages
exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Database\Grammar::columnize() must be of the type array, integer given, called in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 111 and defined' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:95
Stack trace:
#0 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(95): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', '/home/htdocs/tu...', 95, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(111): Illuminate\Database\Grammar->columnize(9)
#2 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(66): Illuminate\Database\Query\Grammars\Grammar->compileColumns(Object(Illuminate\Database\Query\Builder), 9)
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(44): Illuminate\Database\Query\Grammars\Grammar->compileComponents(Object(Illuminate\Database\Query\Builder))
#4 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(940): Illuminate\Database\Query\Grammars\Grammar->compileSelect(Object(Illuminate\Database\Query\Builder))
#5 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1028): Illuminate\Database\Query\Builder->toSql()
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#7 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(9)
#8 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(441): Illuminate\Database\Query\Builder->get(9)
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(132): Illuminate\Database\Eloquent\Builder->getModels(9)
#10 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(108): Illuminate\Database\Eloquent\Builder->get(9)
#11 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(69): Illuminate\Database\Eloquent\Builder->first(9)
#12 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(484): Illuminate\Database\Eloquent\Builder->find(11, 9)
#13 /home/htdocs/turnos/app/controllers/MessagesControler.php(97): Illuminate\Database\Eloquent\Model::find(11, 9)
#14 [internal function]: MessagesController->store()
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#16 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#25 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#26 {main} [] []
[2014-09-05 12:54:21] log.ERROR: 500 - [] operator not supported for strings @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message '[] operator not supported for strings' in /home/htdocs/turnos/app/controllers/MessagesControler.php:91
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 13:01:14] log.ERROR: 500 - syntax error, unexpected ';' @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /home/htdocs/turnos/app/controllers/MessagesControler.php:97
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 13:01:25] log.ERROR: 500 - array_key_exists(): The first argument should be either a string or an integer @ /messages
exception 'ErrorException' with message 'array_key_exists(): The first argument should be either a string or an integer' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Support/Collection.php:67
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_key_exist...', '/home/htdocs/tu...', 67, Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Support/Collection.php(67): array_key_exists(Array, Array)
#2 /home/htdocs/turnos/app/controllers/MessagesControler.php(97): Illuminate\Support\Collection->get(Array)
#3 [internal function]: MessagesController->store()
#4 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#5 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#10 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#14 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#15 {main} [] []
[2014-09-05 13:03:52] log.ERROR: 500 - SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `messages` (`mcname`, `mcnumtel`, `status`, `mensaje`, `user_id`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'ttttttttttttt',
  1 => '1233213213',
  2 => 0,
  3 => 'sssssssssssssssssss',
  4 => NULL,
  5 => '2014-09-05 13:03:52',
  6 => '2014-09-05 13:03:52',
)) @ /messages
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Connection.php:331
Stack trace:
#0 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): PDOStatement->execute(Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `me...', Array)
#2 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Connection.php(332): Illuminate\Database\Connection->run('insert into `me...', Array, Object(Closure))
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Connection.php(289): Illuminate\Database\Connection->statement('insert into `me...', Array)
#4 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `me...', Array)
#5 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `me...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#8 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 /home/htdocs/turnos/app/controllers/MessagesControler.php(110): Illuminate\Database\Eloquent\Model->save()
#13 [internal function]: MessagesController->store()
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#16 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#24 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#25 {main}

Next exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `messages` (`mcname`, `mcnumtel`, `status`, `mensaje`, `user_id`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'ttttttttttttt',
  1 => '1233213213',
  2 => 0,
  3 => 'sssssssssssssssssss',
  4 => NULL,
  5 => '2014-09-05 13:03:52',
  6 => '2014-09-05 13:03:52',
))' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556
Stack trace:
#0 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `me...', Array)
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Connection.php(332): Illuminate\Database\Connection->run('insert into `me...', Array, Object(Closure))
#2 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Connection.php(289): Illuminate\Database\Connection->statement('insert into `me...', Array)
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `me...', Array)
#4 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `me...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(786): call_user_func_array(Array, Array)
#7 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 /home/htdocs/turnos/app/controllers/MessagesControler.php(110): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: MessagesController->store()
#13 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#14 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('store', Array)
#15 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'store', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#18 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#19 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#23 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#24 {main} [] []
[2014-09-05 13:11:27] log.ERROR: 404 - Exception @ /mesagges/4/edit
exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429
Stack trace:
#0 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#5 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#6 {main} [] []
[2014-09-05 13:16:17] log.ERROR: 500 - Call to a member function delete() on a non-object @ /messages/3
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function delete() on a non-object' in /home/htdocs/turnos/app/controllers/MessagesControler.php:219
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 13:27:55] log.ERROR: 404 - Exception @ /mesagges/10/edit
exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429
Stack trace:
#0 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /home/htdocs/turnos/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /home/htdocs/turnos/public/index.php(49): Illuminate\Foundation\Application->run()
#5 /home/htdocs/turnos/server.php(19): require_once('/home/htdocs/tu...')
#6 {main} [] []
[2014-09-05 14:50:04] log.ERROR: 500 - syntax error, unexpected 'endforeach' (T_ENDFOREACH) @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'endforeach' (T_ENDFOREACH)' in /home/htdocs/turnos/app/storage/views/01e7aecac1b08f84c4ae3a208d4f3789:74
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 14:52:00] log.ERROR: 500 - syntax error, unexpected 'elseif' (T_ELSEIF) @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'elseif' (T_ELSEIF)' in /home/htdocs/turnos/app/storage/views/01e7aecac1b08f84c4ae3a208d4f3789:51
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 14:52:20] log.ERROR: 500 - syntax error, unexpected 'else' (T_ELSE) @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'else' (T_ELSE)' in /home/htdocs/turnos/app/storage/views/01e7aecac1b08f84c4ae3a208d4f3789:51
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-09-05 14:53:06] log.ERROR: 500 - syntax error, unexpected 'else' (T_ELSE) @ /messages
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'else' (T_ELSE)' in /home/htdocs/turnos/app/storage/views/01e7aecac1b08f84c4ae3a208d4f3789:51
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
